### ISSUE TITLE
improve exception trace report in h5structure

### ISSUE THREAD

**Issue by prjemian** [prjemian/punx#22]
Hard to diagnose the problem with user's data file from this exception report:

	> user@AirBook:~/Data punx structure !$
	> punx structure file_master.h5
	> Traceback (most recent call last):
	>   File "/sw/bin/punx", line 9, in <module>
	>     load_entry_point('punx==0+unknown', 'console_scripts', 'punx')()
	>   File "/sw/lib/python2.7/site-packages/punx/main.py", line 210, in main
	>     args.func(args)
	>   File "/sw/lib/python2.7/site-packages/punx/main.py", line 106, in
	> func_structure
	>     print '\n'.join(mc.report(show_attributes) or '')
	>   File "/sw/lib/python2.7/site-packages/punx/h5structure.py", line 58,
	> in report
	>     structure = self._renderGroup(f, txt, indentation = "")
	>   File "/sw/lib/python2.7/site-packages/punx/h5structure.py", line 109,
	> in _renderGroup
	>     s += self._renderGroup(value, itemname, indentation+"  ")
	>   File "/sw/lib/python2.7/site-packages/punx/h5structure.py", line 109,
	> in _renderGroup
	>     s += self._renderGroup(value, itemname, indentation+"  ")
	>   File "/sw/lib/python2.7/site-packages/punx/h5structure.py", line 97,
	> in _renderGroup
	>     s += self._renderDataset(value, itemname, indentation+"  ")
	>   File "/sw/lib/python2.7/site-packages/punx/h5structure.py", line 158,
	> in _renderDataset
	>     value = self._renderArray(dset, indentation + '  ')
	>   File "/sw/lib/python2.7/site-packages/punx/h5structure.py", line 205,
	> in _renderArray
	>     r = self._renderNdArray(obj, indentation + '  ')
	>   File "/sw/lib/python2.7/site-packages/punx/h5structure.py", line 234,
	> in _renderNdArray
	>     r.append( __render(obj, rank, i, indentation + '  ') )
	>   File "/sw/lib/python2.7/site-packages/punx/h5structure.py", line 224,
	> in __render
	>     part = eval('obj[%s]' % indices)
	>   File "<string>", line 1, in <module>
	>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
	> (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2687)
	>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
	> (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2645)
	>   File "/sw/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 482,
	> in __getitem__
	>     self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
	>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
	> (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2687)
	>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
	> (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2645)
	>   File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read
	> (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/h5d.c:3231)
	>   File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
	> (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_proxy.c:1860)
	>   File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
	> (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_proxy.c:1508)
	> IOError: Can't read data (Can't stat file: no such file or directory)

**Comment by prjemian** [comment]
This IOError was fixed by #39
