### ISSUE TITLE
validate: KeyError: ExternalLink file missing

### ISSUE THREAD

**Issue by prjemian** [prjemian/punx#240]
Using v0.3.4, `punx validate master.h5` (with ExternalLink to `'t_001553.h5'`) raised this `KeyError` exception:

```py
(bluesky_2023_2) 8idiuser@agate .../sandbox/20230915 $ punx val  ../20230912/20230912-151125-S38086-39dd525.hdf 

!!! WARNING: this program is not ready for distribution.

Traceback (most recent call last):
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2023_2/bin/punx", line 10, in <module>
    sys.exit(main())
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2023_2/lib/python3.10/site-packages/punx/main.py", line 441, in main
    args.func(args)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2023_2/lib/python3.10/site-packages/punx/main.py", line 228, in func_validate
    validator.validate(args.infile)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2023_2/lib/python3.10/site-packages/punx/validate.py", line 237, in validate
    self.build_address_catalog()
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2023_2/lib/python3.10/site-packages/punx/validate.py", line 267, in build_address_catalog
    self._group_address_catalog_(None, self.h5)
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2023_2/lib/python3.10/site-packages/punx/validate.py", line 295, in _group_address_catalog_
    self._group_address_catalog_(parent, group[item])
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2023_2/lib/python3.10/site-packages/punx/validate.py", line 295, in _group_address_catalog_
    self._group_address_catalog_(parent, group[item])
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2023_2/lib/python3.10/site-packages/punx/validate.py", line 295, in _group_address_catalog_
    self._group_address_catalog_(parent, group[item])
  [Previous line repeated 3 more times]
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2023_2/lib/python3.10/site-packages/punx/validate.py", line 294, in _group_address_catalog_
    if utils.isHdf5Group(group[item]):
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/beams/8IDIUSER/.conda/envs/bluesky_2023_2/lib/python3.10/site-packages/h5py/_hl/group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to synchronously open object (unable to open external file, external link file name = 't_001553.h5')"
```

**Comment by prjemian** [comment]
Looks like the same problem resolved in #233 for `punx tree`.
