### ISSUE TITLE
TypeError exception when validating non-NeXus HDF5 file

### ISSUE THREAD

**Issue by prjemian** [prjemian/punx#25]
mintadmin@mintadmin-VirtualBox ~ $ punx validate /home/mintadmin/Apps/anaconda/pkgs/bokeh-0.8.1-np19py27_1/lib/python2.7/site-packages/bokeh/server/tests/data/AAPL.hdf5
	Traceback (most recent call last):
	  File "/home/mintadmin/Apps/anaconda/bin/punx", line 11, in <module>
		sys.exit(main())
	  File "/home/mintadmin/Apps/anaconda/lib/python2.7/site-packages/punx/main.py", line 326, in main
		args.func(args)
	  File "/home/mintadmin/Apps/anaconda/lib/python2.7/site-packages/punx/main.py", line 157, in func_validate
		validator.validate()
	  File "/home/mintadmin/Apps/anaconda/lib/python2.7/site-packages/punx/validate.py", line 559, in validate
		self.validate_group(obj, 'NXentry')
	  File "/home/mintadmin/Apps/anaconda/lib/python2.7/site-packages/punx/validate.py", line 588, in validate_group
		self.validate_attributes(group, nx_class)
	  File "/home/mintadmin/Apps/anaconda/lib/python2.7/site-packages/punx/validate.py", line 673, in validate_attributes
		msg = 'unknown: ' + nxdl_class
	TypeError: cannot concatenate 'str' and 'NoneType' objects
	mintadmin@mintadmin-VirtualBox ~ $

**Comment by prjemian** [comment]
fixed by #26
