### ISSUE TITLE
IOError reading HDF5 files

### ISSUE THREAD

**Issue by prjemian** [prjemian/punx#39]
Received a sample file set from Diamond Light Source with data from the Eiger detector.

Neither structure nor validate can handle this yet.  Here's the exception:

     jemian@gov ~/Downloads $ punx st PB103A_2_98_master.h5
     Traceback (most recent call last):
       File "/home/oxygen/JEMIAN/Apps/anaconda/bin/punx", line 9, in <module>
     	 load_entry_point('punx==0.0.6+6.g2614f69', 'console_scripts', 'punx')()
       File "/local/Apps/anaconda/lib/python2.7/site-packages/punx/main.py", line 387, in main
     	 args.func(args)
       File "/local/Apps/anaconda/lib/python2.7/site-packages/punx/main.py", line 159, in func_structure
     	 report = mc.report(show_attributes)
       File "/local/Apps/anaconda/lib/python2.7/site-packages/punx/h5structure.py", line 90, in report
     	 structure = self._renderGroup(f, txt, indentation = "")
       File "/local/Apps/anaconda/lib/python2.7/site-packages/punx/h5structure.py", line 141, in _renderGroup
     	 s += self._renderGroup(value, itemname, indentation+"  ")
       File "/local/Apps/anaconda/lib/python2.7/site-packages/punx/h5structure.py", line 141, in _renderGroup
     	 s += self._renderGroup(value, itemname, indentation+"  ")
       File "/local/Apps/anaconda/lib/python2.7/site-packages/punx/h5structure.py", line 129, in _renderGroup
     	 s += self._renderDataset(value, itemname, indentation+"  ")
       File "/local/Apps/anaconda/lib/python2.7/site-packages/punx/h5structure.py", line 200, in _renderDataset
     	 value = self._renderArray(dset, indentation + '  ')
       File "/local/Apps/anaconda/lib/python2.7/site-packages/punx/h5structure.py", line 247, in _renderArray
     	 r = self._renderNdArray(obj, indentation + '  ')
       File "/local/Apps/anaconda/lib/python2.7/site-packages/punx/h5structure.py", line 279, in _renderNdArray
     	 r.append( __render(obj, rank, i, indentation + '  ') )
       File "/local/Apps/anaconda/lib/python2.7/site-packages/punx/h5structure.py", line 269, in __render
     	 part = eval('obj[%s]' % indices)
       File "<string>", line 1, in <module>
       File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2582)
       File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2541)
       File "/local/Apps/anaconda/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 482, in __getitem__
     	 self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
       File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2582)
       File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2541)
       File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read (-------src-dir-------/h5py/h5d.c:3128)
       File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw (-------src-dir-------/h5py/_proxy.c:1774)
       File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread (-------src-dir-------/h5py/_proxy.c:1416)
     IOError: Can't read data (Can't open directory)

**Comment by prjemian** [comment]
validate handles it, only structure throws the exception

hunch:  error might be due to the new HDF5 library version with the SWMR feature
