### ISSUE TITLE
Cannot validate file: example_mapping.nxs

### ISSUE THREAD

**Issue by prjemian** [prjemian/punx#53]
Testing against the file [example_mapping.nxs](https://github.com/nexusformat/features/blob/master/examples/example_mapping.nxs), this exception trace was produced:

	PS C:\Users\Pete\Downloads> punx va .\example_mapping.nxs
	Traceback (most recent call last):
	  File "D:\Apps\Anaconda\Scripts\punx-script.py", line 9, in <module>
		load_entry_point('punx==0.0.9', 'console_scripts', 'punx')()
	  File "D:\Apps\Anaconda\lib\site-packages\punx\main.py", line 406, in main
		args.func(args)
	  File "D:\Apps\Anaconda\lib\site-packages\punx\main.py", line 205, in func_validate
		validator.validate()
	  File "D:\Apps\Anaconda\lib\site-packages\punx\validate.py", line 247, in validate
		self.validate_HDF5_group(self.h5)
	  File "D:\Apps\Anaconda\lib\site-packages\punx\validate.py", line 325, in validate_HDF5_group
		self.validate_HDF5_group(child)
	  File "D:\Apps\Anaconda\lib\site-packages\punx\validate.py", line 325, in validate_HDF5_group
		self.validate_HDF5_group(child)
	  File "D:\Apps\Anaconda\lib\site-packages\punx\validate.py", line 337, in validate_HDF5_group
		self.validate_NXDL_specification(group, nx_class_name)
	  File "D:\Apps\Anaconda\lib\site-packages\punx\validate.py", line 447, in validate_NXDL_specification
		self.validate_NXDL_field_specification(field_name, group, rules)
	  File "D:\Apps\Anaconda\lib\site-packages\punx\validate.py", line 539, in validate_NXDL_field_specification
		t = type(v) in self.data_types[attr_type]
	KeyError: 'str'

In addition to the exception, there is no indication what object in the HDF5 file triggered the exception.

**Comment by prjemian** [comment]
In nxdl.xsd, ``interpretation`` is defined as type ``xs:string`` (as other are similar enumerations).  This validation code is expecting a NeXus data type, such as ``NX_CHAR``.

This validation should trap such an occurrence **BUT** perhaps the NeXus ``nxdl.xsd`` file could be similarly revised?
