### ISSUE TITLE
py3 validate AttributeError

### ISSUE THREAD

**Issue by prjemian** [prjemian/punx#56]
jemian@gov .../oxygen18/JEMIAN $ /local/Apps/anaconda3/x86_64/bin/punx demo
    console> punx validate /local/Apps/anaconda3/x86_64/lib/python3.5/site-packages/punx/data/writer_1_3.hdf5
    Traceback (most recent call last):
      File "/local/Apps/anaconda3/x86_64/bin/punx", line 11, in <module>
    	sys.exit(main())
      File "/local/Apps/anaconda3/x86_64/lib/python3.5/site-packages/punx/main.py", line 412, in main
    	args.func(args)
      File "/local/Apps/anaconda3/x86_64/lib/python3.5/site-packages/punx/main.py", line 119, in func_demo
    	func_validate(args)
      File "/local/Apps/anaconda3/x86_64/lib/python3.5/site-packages/punx/main.py", line 182, in func_validate
    	validator = validate.Data_File_Validator(args.infile)
    AttributeError: module 'validate' has no attribute 'Data_File_Validator'

**Comment by prjemian** [comment]
not a problem with py2

**Comment by prjemian** [comment]
could not reproduce when tried on another workstation, will investigate installation issues on reporting workstation
