### ISSUE TITLE
IndexError: when reading file from BlueSky NeXus writer

### ISSUE THREAD

**Issue by prjemian** [prjemian/punx#87]
I've [proposed](https://github.com/NSLS-II/suitcase/pull/31) a [NeXus data file writer](https://github.com/BCDA-APS/suitcase/blob/NeXus-dev/suitcase/nexus.py) to the BlueSky project.

Current version of punx (0.1.8) fails with IndexError while [h5toText](https://github.com/prjemian/spec2nexus/blob/master/src/spec2nexus/h5toText.py) from `spec2nexus` does not.  What's up with that?

full report:

    jemian@gov .../EPICSADM/sandbox $ punx st developer_3.h5 
    Traceback (most recent call last):
      File "/home/oxygen/JEMIAN/Apps/anaconda/bin/punx", line 11, in <module>
        sys.exit(main())
      File "/local/Apps/anaconda/lib/python2.7/site-packages/punx/main.py", line 410, in main
        args.func(args)
      File "/local/Apps/anaconda/lib/python2.7/site-packages/punx/main.py", line 162, in func_structure
        report = mc.report(show_attributes)
      File "/local/Apps/anaconda/lib/python2.7/site-packages/punx/h5structure.py", line 103, in report
        structure = self._renderGroup(f, txt, indentation = "")
      File "/local/Apps/anaconda/lib/python2.7/site-packages/punx/h5structure.py", line 155, in _renderGroup
        s += self._renderGroup(value, itemname, indentation+"  ")
      File "/local/Apps/anaconda/lib/python2.7/site-packages/punx/h5structure.py", line 155, in _renderGroup
        s += self._renderGroup(value, itemname, indentation+"  ")
      File "/local/Apps/anaconda/lib/python2.7/site-packages/punx/h5structure.py", line 143, in _renderGroup
        s += self._renderDataset(value, itemname, indentation+"  ")
      File "/local/Apps/anaconda/lib/python2.7/site-packages/punx/h5structure.py", line 237, in _renderDataset
        s += self._renderAttributes(dset, indentation)
      File "/local/Apps/anaconda/lib/python2.7/site-packages/punx/h5structure.py", line 167, in _renderAttributes
        if isinstance(value[0], (bytes, numpy.bytes_)):
    IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by prjemian** [comment]
[developer_3.tree.txt](https://github.com/prjemian/punx/files/851201/developer_3.tree.txt)

![scan3](https://cloud.githubusercontent.com/assets/2279984/24053160/1c85e5ce-0b06-11e7-899e-2da2d509d5ea.png)

**Comment by prjemian** [comment]
[developer_3.zip](https://github.com/prjemian/punx/files/851204/developer_3.zip)

**Comment by prjemian** [comment]
the code in bluesky is out of date and the h5structure module has been replaced, closing this wontfix issue now
